
import __ASTRO_IMAGE_IMPORT_lRm98 from "./assets/agent-skills.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fagent-skills-empower-ai-drupal.md";
import __ASTRO_IMAGE_IMPORT_19AJI9 from "./assets/D10-withoutMCP-small.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbuilding-local-drupal-api-mcp-server.md";
import __ASTRO_IMAGE_IMPORT_AMIko from "./assets/D10-withMCP-small.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbuilding-local-drupal-api-mcp-server.md";
import __ASTRO_IMAGE_IMPORT_ZK0wDI from "./assets/D11-withMCP-small.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbuilding-local-drupal-api-mcp-server.md";
import __ASTRO_IMAGE_IMPORT_1gnyLp from "./assets/building-version-aware-mcp.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbuilding-local-drupal-api-mcp-server.md";
import __ASTRO_IMAGE_IMPORT_Z1hC1Om from "./assets/context-is-key.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcontext-is-key-but-missing.md";
import __ASTRO_IMAGE_IMPORT_Z2qmMBA from "./assets/ai_context.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhackathon-european-commission-2026.md";
import __ASTRO_IMAGE_IMPORT_1Dr6QF from "./assets/content.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhackathon-european-commission-2026.md";
import __ASTRO_IMAGE_IMPORT_Z27GbR4 from "./assets/score.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhackathon-european-commission-2026.md";
import __ASTRO_IMAGE_IMPORT_zCuqp from "./assets/trend.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhackathon-european-commission-2026.md";
import __ASTRO_IMAGE_IMPORT_1DhiL5 from "./assets/neo4j-accordion-5.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhackathon-european-commission-2026.md";
import __ASTRO_IMAGE_IMPORT_Z1m0if4 from "./assets/ace.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhackathon-european-commission-2026.md";
import __ASTRO_IMAGE_IMPORT_2bpMOK from "./assets/is-there-ai-in-team.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fis-there-an-ai-in-team.md";
import __ASTRO_IMAGE_IMPORT_16uAdB from "./assets/antoni-gaudi-community-experience-building-dall-e.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fdrupalcon-2024-barcelona.md";
import __ASTRO_IMAGE_IMPORT_Z2iFhk7 from "./assets/pexels-jplenio-1118874.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkeep-swimming-in-the-ai-storm.md";
import __ASTRO_IMAGE_IMPORT_Z2qFEJx from "./assets/agent-trace-update.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgit-blame-intent-aware-agents.md";
import __ASTRO_IMAGE_IMPORT_Z4MPiP from "./assets/pexels-jplenio-1118874.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fnavigating-the-ai-storm.md";
export default new Map([["./assets/agent-skills.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fagent-skills-empower-ai-drupal.md", __ASTRO_IMAGE_IMPORT_lRm98], ["./assets/D10-withoutMCP-small.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbuilding-local-drupal-api-mcp-server.md", __ASTRO_IMAGE_IMPORT_19AJI9], ["./assets/D10-withMCP-small.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbuilding-local-drupal-api-mcp-server.md", __ASTRO_IMAGE_IMPORT_AMIko], ["./assets/D11-withMCP-small.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbuilding-local-drupal-api-mcp-server.md", __ASTRO_IMAGE_IMPORT_ZK0wDI], ["./assets/building-version-aware-mcp.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbuilding-local-drupal-api-mcp-server.md", __ASTRO_IMAGE_IMPORT_1gnyLp], ["./assets/context-is-key.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcontext-is-key-but-missing.md", __ASTRO_IMAGE_IMPORT_Z1hC1Om], ["./assets/ai_context.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhackathon-european-commission-2026.md", __ASTRO_IMAGE_IMPORT_Z2qmMBA], ["./assets/content.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhackathon-european-commission-2026.md", __ASTRO_IMAGE_IMPORT_1Dr6QF], ["./assets/score.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhackathon-european-commission-2026.md", __ASTRO_IMAGE_IMPORT_Z27GbR4], ["./assets/trend.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhackathon-european-commission-2026.md", __ASTRO_IMAGE_IMPORT_zCuqp], ["./assets/neo4j-accordion-5.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhackathon-european-commission-2026.md", __ASTRO_IMAGE_IMPORT_1DhiL5], ["./assets/ace.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhackathon-european-commission-2026.md", __ASTRO_IMAGE_IMPORT_Z1m0if4], ["./assets/is-there-ai-in-team.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fis-there-an-ai-in-team.md", __ASTRO_IMAGE_IMPORT_2bpMOK], ["./assets/antoni-gaudi-community-experience-building-dall-e.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fdrupalcon-2024-barcelona.md", __ASTRO_IMAGE_IMPORT_16uAdB], ["./assets/pexels-jplenio-1118874.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkeep-swimming-in-the-ai-storm.md", __ASTRO_IMAGE_IMPORT_Z2iFhk7], ["./assets/agent-trace-update.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fgit-blame-intent-aware-agents.md", __ASTRO_IMAGE_IMPORT_Z2qFEJx], ["./assets/pexels-jplenio-1118874.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fnavigating-the-ai-storm.md", __ASTRO_IMAGE_IMPORT_Z4MPiP]]);
		